export const ADMIN_SAVE = 'ADMIN_SAVE';
export const ADMIN_REMOVE = 'ADMIN_REMOVE';

export const GET_ADMIN_BEGIN='GET_ADMIN_BEGIN';
export const GET_ADMIN_SUCCESS='GET_ADMIN_SUCCESS';
export const GET_ADMIN_FAIL='GET_ADMIN_FAIL';