export const USER_SAVE = 'USER_SAVE';
export const USER_REMOVE = 'USER_REMOVE';

export const GET_USER_AVTAR_BEGIN='GET_USER_AVTAR_BEGIN';
export const GET_USER_AVTAR_SUCCESS='GET_USER_AVTAR_SUCCESS';
export const GET_USER_AVTAR_FAIL='GET_USER_AVTAR_FAIL';
